services:
  komga:
    image: ghcr.io/gotson/komga:1.22.1
    container_name: komga
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/data:/data
      - ${ROOT_FOLDER_HOST}/media:/media
    user: "1000:1000"
    environment:
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:25600
    networks:
      - tipi_main_network
    restart: unless-stopped
    labels:
      runtipi.managed: true
