services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:2.26.1
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/spoken:/audiobooks
      - ${ROOT_FOLDER_HOST}/media/data/podcasts:/podcasts
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/metadata:/metadata
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
